
// Objective-C API for talking to the following Go packages
//
//	gomobilelib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GomobileNative_FRAMEWORK_H__
#define __GomobileNative_FRAMEWORK_H__

#include "GomobileNative.objc.h"
#include "Universe.objc.h"

#endif
