// Objective-C API for talking to gomobilelib Go package.
//   gobind -lang=objc gomobilelib
//
// File is generated by gobind. Do not edit.

#ifndef __GomobileNative_H__
#define __GomobileNative_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GomobileNativeBird;
@class GomobileNativeGoMobileLib;

@interface GomobileNativeBird : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull species;
@property (nonatomic) NSString* _Nonnull description;
@end

@interface GomobileNativeGoMobileLib : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSData* _Nullable)getBirdInfo:(NSString* _Nullable)bird;
- (NSData* _Nullable)getBirds;
- (long)randomNumber;
@end

FOUNDATION_EXPORT GomobileNativeGoMobileLib* _Nullable GomobileNativeGetInstance(void);

#endif
